services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Generated\Normalizer\JaneObjectNormalizer: ~

  Generated\Client:
    factory: ['Generated\Client', 'create']
    lazy: true
